[package]
title = "Smart Information"
version = "1.0.0"
description = "Displays Inventec_Tester USD custom data."
authors = ["Zin"]
repository = "https://github.com/DockorSherowLinZ/Zin_All_Tools"
keywords = ["omniverse", "kit", "extension", "tw.zin"]
category = "ZinTools"

[dependencies]
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.uiapp" = {}
"omni.ui.scene" = {}
"omni.kit.viewport.utility" = {}

[[python.module]]
name = "smart_information"
